ats:
- greenhouse:
    endpoint: "https://boards-api.greenhouse.io/v1/boards/{token}/jobs"
    companies:
    - name: "A-TEK"
      token: "atek"
    - name: "Adyen"
      token: "adyen"
    - name: "Affinidi"
      token: "affinidi"
    - name: "Aircall"
      token: "aircallioinc"
    - name: "Algolia"
      token: "algolia"
    - name: "Alma"
      token: "alma31"
    - name: "Anthropic"
      token: "anthropic"
    - name: "Artefact"
      token: "artefact"
    - name: "Asana"
      token: "asana"
    - name: "AutoScout24"
      token: "autoscout24"
    - name: "B-Stock"
      token: "bstocksolutions"
    - name: "Brex"
      token: "brex"
    - name: "Celonis"
      token: "celonis"
    - name: "Chime"
      token: "chime"
    - name: "CLEAR"
      token: "clear"
    - name: "Cloudflare"
      token: "cloudflare"
    - name: "Coinbase"
      token: "coinbase"
    - name: "Contentful"
      token: "contentful"
    - name: "Cresta"
      token: "cresta"
    - name: "Customer.io"
      token: "customerio"
    - name: "Dashlane"
      token: "dashlane"
    - name: "Databricks"
      token: "databricks"
    - name: "Datadog"
      token: "datadog"
    - name: "Dataiku"
      token: "dataiku"
    - name: "Diligent"
      token: "diligent"
    - name: "Doctolib"
      token: "doctolib"
    - name: "Dropbox"
      token: "dropbox"
    - name: "Elastic"
      token: "elastic"
    - name: "EvolutionIQ"
      token: "evolutioniq"
    - name: "Figma"
      token: "figma"
    - name: "Fireblocks"
      token: "fireblocks"
    - name: "Five Rings"
      token: "fiveringsllc"
    - name: "Flow Traders"
      token: "flowtraders"
    - name: "GetYourGuide"
      token: "getyourguide"
    - name: "GitLab"
      token: "gitlab"
    - name: "Gong"
      token: "gongio"
    - name: "Grafana Labs"
      token: "grafanalabs"
    - name: "Graphcore"
      token: "graphcore"
    - name: "GROPYUS"
      token: "gropyus"
    - name: "GuidePoint Security"
      token: "guidepointsecurity"
    - name: "Heartflow"
      token: "heartflowinc"
    - name: "IDnow"
      token: "idnow"
    - name: "IMC Trading"
      token: "imc"
    - name: "Intercom"
      token: "intercom"
    - name: "Interstellar Lab"
      token: "interstellarlab"
    - name: "Jump Trading"
      token: "jumptrading"
    - name: "Kaizen Gaming"
      token: "kaizengaming"
    - name: "Mercury"
      token: "mercury"
    - name: "Mirakl"
      token: "mirakl"
    - name: "Mixpanel"
      token: "mixpanel"
    - name: "MongoDB"
      token: "mongodb"
    - name: "Monzo"
      token: "monzo"
    - name: "Mozilla"
      token: "mozilla"
    - name: "N26"
      token: "n26"
    - name: "Okta"
      token: "okta"
    - name: "Optiver"
      token: "optiver"
    - name: "Proton"
      token: "proton"
    - name: "Proton.ai"
      token: "protonai"
    - name: "Reddit"
      token: "reddit"
    - name: "Robinhood"
      token: "robinhood"
    - name: "Samsara"
      token: "samsara"
    - name: "Scale AI"
      token: "scaleai"
    - name: "Shift Technology"
      token: "shifttechnology"
    - name: "SoFi"
      token: "sofi"
    - name: "Speechify"
      token: "speechify"
    - name: "Speechmatics"
      token: "speechmatics"
    - name: "Sprout Social"
      token: "sproutsocial"
    - name: "Stripe"
      token: "stripe"
    - name: "Tanium"
      token: "tanium"
    - name: "TheFork"
      token: "thefork"
    - name: "Thunes"
      token: "thunes"
    - name: "Toast"
      token: "toast"
    - name: "Together AI"
      token: "togetherai"
    - name: "Tripadvisor"
      token: "tripadvisor"
    - name: "Twilio"
      token: "twilio"
    - name: "Vercel"
      token: "vercel"
    - name: "Verifone"
      token: "verifone"
    - name: "Virtu Financial"
      token: "virtu"
    - name: "Wolt"
      token: "wolt"
    - name: "xAI"
      token: "xai"
    - name: "Zeta Global"
      token: "zetaglobal"

- ashbyhq:
    endpoint: "https://api.ashbyhq.com/posting-api/job-board/{token}"
    companies:
    - name: "Amplitude"
      token: "amplitude"
    - name: "Back Market"
      token: "backmarket"
    - name: "DeepL"
      token: "deepl"
    - name: "Docker"
      token: "docker"
    - name: "Linear"
      token: "linear"
    - name: "Mistral AI"
      token: "mistral.ai"
    - name: "Notion"
      token: "notion"
    - name: "OpenSea"
      token: "opensea"
    - name: "Ramp"
      token: "ramp"
    - name: "Supabase"
      token: "supabase"
    - name: "Vocca"
      token: "vocca"

- lever:
    endpoint: "https://api.lever.co/v0/postings/{token}"
    companies:
    - name: "Blablacar"
      token: "blablacar"
    - name: "Brevo"
      token: "brevo"
    - name: "Contentsquare"
      token: "contentsquare"
    - name: "Swile"
      token: "swile"
    - name: "Pigment"
      token: "pigment"
    - name: "Qonto"
      token: "qonto"

# - workable:
#     endpoint: "https://apply.workable.com/api/v1/widget/accounts/{token}?details=true"
#     companies:
#     - name: "Exotec"
#       token: "exotec"
#     - name: "Hugging Face"
#       token: "huggingface"
